recipe-modal-commit
georgijbudik/project-tastytreats pull request #5
Opened 2023-08-18 16:01 UTC by Ivan011001

у цілому, тут працююче модальне вікно з детальною інформацією. поки що висить заглушка, трохи пізніше додам функціонал згідно з яким інформація буде завантажуватись на основі даних з беку. є одна проблема - висота вікна. на макети вона 905рх, однак це значно більше ніж висота екрану, тому я поставив 705рх, тому аби вмістити увесь контент, я додав скрол, а оскільки дефолтний скрол не дуже гарний, його потрібно кастомно змінити. цим я займусь завтра, так само як і адаптивом. наче все)

2023-08-18 18:31 UTC, georgijbudik commented
Привіт, все добре, але при відкритті модалки потрібно кидати eventlistener на window і по закриттю убирати його, а в колл бек кинути окрему функцію яка якраз закриває модалку по кліку на Esc і також потрібно додати eventlistener на саму модалку і в коллбек кинути функцію закриття модалки кліком по фону

2023-08-18 18:33 UTC, georgijbudik requested changes
Привіт, все добре, але при відкритті модалки потрібно кидати eventlistener на window і по закриттю убирати його, а в колл бек кинути окрему функцію яка якраз закриває модалку по кліку на Esc і також потрібно додати eventlistener на саму модалку і в коллбек кинути функцію закриття модалки кліком по фону

2023-08-18 20:55 UTC, Ivan011001 commented
переробив, чекаю на перевірку)

2023-08-18 21:48 UTC, georgijbudik commented
все топ, тільки ми кидаємо eventlistener на window а не на документ

2023-08-19 11:34 UTC, Ivan011001 commented
Виконав адаптив, приховав дефолтний скролбар. Сьогодні розберусь із зірочками та напишу функцію, що буде рендерити модалку завдяки даним з беку

2023-08-19 11:35 UTC, merged